# Generated by Django 4.2.3 on 2023-07-25 14:16

import bakecake_site.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, default='some_user', max_length=250, verbose_name='Имя')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Адрес электронной почты')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является сотрудником')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
            managers=[
                ('objects', bakecake_site.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ягоды')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Декор')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Формы')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Уровень')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Топпинг')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес')),
                ('date', models.DateField(verbose_name='Дата доставки')),
                ('time', models.TimeField(verbose_name='Время доставки')),
                ('status', models.CharField(choices=[('1', 'Ожидает оплаты'), ('2', 'Принят к обработке'), ('3', 'Готовится'), ('4', 'Передан в доставку'), ('5', 'Завершен')], default='1', max_length=20, verbose_name='Статус заказа')),
                ('berries', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.berries', verbose_name='Ягоды')),
                ('decor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.decor', verbose_name='Декор')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.form', verbose_name='Форма')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.level', verbose_name='Уровень')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.topping', verbose_name='Топпинги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
        ),
    ]
