# Generated by Django 4.2.3 on 2023-07-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ready_cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название торта')),
                ('description', models.TextField()),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
    ]
