# Generated by Django 4.2.3 on 2023-07-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscription',
        ),
    ]
