# Generated by Django 4.2.3 on 2023-07-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0002_delete_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='berries',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='decor',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='form',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='level',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
