# Generated by Django 4.2.3 on 2023-07-29 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0003_ready_cakes_index_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_comment',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Комментарий для курьера'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_comment',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
