# Generated by Django 4.2.3 on 2023-07-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0003_berries_price_decor_price_form_price_level_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='berries',
            old_name='price',
            new_name='Цена',
        ),
        migrations.RenameField(
            model_name='decor',
            old_name='price',
            new_name='Цена',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='price',
            new_name='Цена',
        ),
        migrations.RenameField(
            model_name='level',
            old_name='price',
            new_name='Цена',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='price',
            new_name='Цена',
        ),
    ]
