# Generated by Django 4.2.3 on 2023-07-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0004_bitly_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitly_statistic',
            name='number_transitions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество переходов'),
        ),
    ]
