# Generated by Django 4.2.3 on 2023-07-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0004_rename_price_berries_цена_rename_price_decor_цена_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berries',
            name='Цена',
        ),
        migrations.RemoveField(
            model_name='berries',
            name='Ягоды',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='Декор',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='Цена',
        ),
        migrations.RemoveField(
            model_name='form',
            name='Формы',
        ),
        migrations.RemoveField(
            model_name='form',
            name='Цена',
        ),
        migrations.RemoveField(
            model_name='level',
            name='Уровень',
        ),
        migrations.RemoveField(
            model_name='level',
            name='Цена',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='Топпинг',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='Цена',
        ),
        migrations.AddField(
            model_name='berries',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='berries',
            name='title',
            field=models.CharField(default=0, max_length=200, verbose_name='Ягоды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decor',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='decor',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Декор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Формы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='level',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Уровень'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='topping',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Топпинг'),
            preserve_default=False,
        ),
    ]
