# Generated by Django 4.2.3 on 2023-07-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0005_alter_bitly_statistic_number_transitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitly_statistic',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
