# Generated by Django 4.2.3 on 2023-07-24 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0005_remove_berries_цена_remove_berries_ягоды_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес', default=1)),
                ('date', models.DateField(verbose_name='Дата доставки')),
                ('time', models.TimeField(verbose_name='Время доставки')),
                ('status', models.CharField(choices=[('1', 'Ожидает оплаты'), ('2', 'Принят к обработке'), ('3', 'Готовится'), ('4', 'Передан в доставку'), ('5', 'Завершен')], default='1', max_length=20, verbose_name='Статус заказа')),
                ('berries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.berries', verbose_name='Ягоды')),
                ('decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.decor', verbose_name='Декор')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.form', verbose_name='Форма')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.level', verbose_name='Уровень')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.topping', verbose_name='Топпинги')),
            ],
        ),
    ]
