# Generated by Django 4.2.3 on 2023-07-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0006_alter_bitly_statistic_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berries',
            options={'verbose_name': 'Ягода', 'verbose_name_plural': 'Ягоды'},
        ),
        migrations.AlterModelOptions(
            name='bitly_statistic',
            options={'verbose_name': 'Ссылки на Bitly', 'verbose_name_plural': 'Ссылка на Bitly'},
        ),
        migrations.AlterModelOptions(
            name='decor',
            options={'verbose_name': 'Декоры', 'verbose_name_plural': 'Декор'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Форма', 'verbose_name_plural': 'Формы'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='ready_cakes',
            options={'verbose_name': 'Готовые торты', 'verbose_name_plural': 'Готовый торт'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': 'Топпинг', 'verbose_name_plural': 'Топпинги'},
        ),
    ]
