# Generated by Django 4.2.3 on 2023-07-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0007_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='berries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.berries', verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='order',
            name='decor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakecake_site.decor', verbose_name='Декор'),
        ),
    ]
