# Generated by Django 4.2.3 on 2023-07-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake_site', '0004_order_delivery_comment_order_order_comment_and_more'),
        ('bakecake_site', '0007_alter_berries_options_alter_bitly_statistic_options_and_more'),
    ]

    operations = [
    ]
